CREATE SCHEMA xtcid;
ALTER SCHEMA xtcid OWNER TO admin;

REVOKE ALL ON SCHEMA xtcid FROM PUBLIC;
REVOKE ALL ON SCHEMA xtcid FROM admin;
GRANT ALL ON SCHEMA xtcid TO admin;
GRANT ALL ON SCHEMA xtcid TO xtrole;

